config/routes.rb
Premin::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "dashboard/index"

  devise_for :users

  get "home/index"
  match "/customers" => "home#customers"
  match "/about" => "home#about"
  match "/contact" => "home#contact"
  match "/oops" => "home#oops"
  match "/news" => "home#news"
  post "/subscribe" => "mailing_list#create", as: :create_mailinglist_subscription


  constraints(Subdomain) do
    authenticated :user do
      match "/" => "dashboard#index"
    end
    match "/" => "dashboard#public"
    resources :pages
    resources :courses do
      resources :course_sessions
    end
  end

  root :to => 'home#index'

  resources :accounts
end

app/models/course_session.rb
class CourseSession < ActiveRecord::Base
  PENDING  = 0
  OPEN     = 1
  WAITLIST = 2
  FULL     = 3
  CLOSED   = 4

  STATUSES = {
    PENDING  => "Pending",
    OPEN     => "Enrollment Open",
    WAITLIST => "Waitlist",
    FULL     => "Course Full",
    CLOSED   => "Enrollment Closed"
  }
  def self.valid_statuses
    STATUSES.keys
  end

  def status_description
    STATUSES[status]
  end

  belongs_to :course
  attr_accessible :name, :status, :total_capacity, :waitlist_capacity

  # Validations
  validates :name, presence: true
  validates :course, presence: true
  validates :status, inclusion: { in: STATUSES.keys }, presence: true

  scope :by_course, lambda { |course| where("course_sessions.course_id = ?", course.id) }
end

app/controllers/course_sessions_controller.rb
class CourseSessionsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  before_filter :requires_current_account
  before_filter :requires_site_admin, except: [:index, :show]

  # GET /course_sessions
  # GET /course_sessions.json
  def index
    @course = Course.by_account(@current_account).find(params[:course_id])
    @course_sessions = CourseSession.by_course(@course)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @course_sessions }
    end
  end

  # GET /course_sessions/1
  # GET /course_sessions/1.json
  def show
    @course = Course.by_account(@current_account).find(params[:course_id])
    @course_session = CourseSession.by_course(@course).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course_session }
    end
  end

  # GET /course_sessions/new
  # GET /course_sessions/new.json
  def new
    @course = Course.by_account(@current_account).find(params[:course_id])
    @course_session = CourseSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course_session }
    end
  end

  # GET /course_sessions/1/edit
  def edit
    @course_session = CourseSession.find(params[:id])
  end

  # POST /course_sessions
  # POST /course_sessions.json
  def create
    @course = Course.by_account(@current_account).find(params[:course_id])
    @course_session = CourseSession.new(params[:course_session])
    @course_session.course = @course

    respond_to do |format|
      if @course_session.save
        format.html { redirect_to course_course_session_path(@course, @course_session), notice: 'Course session was successfully created.' }
        format.json { render json: @course_session, status: :created, location: course_course_session_path(@course, @course_session) }
      else
        format.html { render action: "new" }
        format.json { render json: @course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /course_sessions/1
  # PUT /course_sessions/1.json
  def update
    @course = Course.by_account(@current_account).find(params[:course_id])
    @course_session = CourseSession.by_course(@course).find(params[:id])

    respond_to do |format|
      if @course_session.update_attributes(params[:course_session])
        format.html { redirect_to course_course_session_path(@course, @course_session), notice: 'Course session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_sessions/1
  # DELETE /course_sessions/1.json
  def destroy
    @course = Course.by_account(@current_account).find(params[:course_id])
    @course_session = CourseSession.by_course(@course).find(params[:id])
    @course_session.destroy

    respond_to do |format|
      format.html { redirect_to course_url(@course) }
      format.json { head :no_content }
    end
  end
end

app/helpers/course_sessions_helper.rb
module CourseSessionsHelper
end

app/views/course_sessions/_form.html.erb
  <% if @course_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_session.errors.count, "error") %> prohibited this course_session from being saved:</h2>

      <ul>
      <% @course_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12">
      <div class="form-group">
        <label><%= f.label :name %></label>
        <%= f.text_field :name, class: "form-control input-large", placeholder: "Session name..." %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <label><%= f.label :status %></label>
        <%= f.select :status, CourseSession::STATUSES.map{|h| [ h[1], h[0] ]}, {}, class: "form-control" %> 
      </div>
    </div>
    <div class="col-lg-4">
      <div class="form-group">
        <label><%= f.label :total_capacity %></label>
        <%= f.text_field :total_capacity, class: "form-control" %>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="form-group">
        <label><%= f.label :waitlist_capacity %></label>
        <%= f.text_field :waitlist_capacity, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">

    <div class="col-lg-4 col-lg-offset-4">
      <div class="btn-group">
        <%= f.submit class: "btn btn-success btn-sm" %>
        <% if buttons.include?(:show) %>
          <%= link_to 'Show', @course_session, class: "btn btn-primary btn-sm" %>
        <% end %>
        <% if buttons.include?(:back) %>
          <%= link_to 'Back', course_course_sessions_path(@course), class: "btn btn-warning btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/course_sessions/edit.html.erb
<h1>Editing course_session</h1>

<%= form_for [@course, @course_session], url: course_course_sessions_path(@course_session) do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
<% end %>

<%= link_to 'Show', @course_session %> |
<%= link_to 'Back', course_course_sessions_path(@course) %>

app/views/course_sessions/index.html.erb
<h1>Listing Course Sessions</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>

<% @course_sessions.each do |course_session| %>
  <tr>
    <td><%= course_session.name %></td>
    <td><%= course_session.status_description %></td>
    <td>
      <div class="btn-group">
        <%= link_to 'Show', course_course_session_path(@course,course_session), class: "btn btn-small btn-primary" %>
        <%= link_to 'Edit', edit_course_course_session_path(@course,course_session), class: "btn btn-small btn-warning" %>
        <%= link_to 'Destroy', course_course_session_path(@course,course_session), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
      </div>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course Session', new_course_course_session_path(@course), class: "btn btn-small btn-success" %>

app/views/course_sessions/new.html.erb
<h1>New Course Session</h1>

<%= form_for [@course, @course_session], url: course_course_sessions_path do |f| %>
  <%= render partial: 'form', locals: { f: f, buttons: [:back] } %>
<% end %>

app/views/course_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_course_course_session_path(@course,@course_session), class: "btn btn-small btn-warning" %>

<%= link_to 'Back', course_course_sessions_path %>