config/routes.rb
Premin::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "dashboard/index"

  devise_for :users

  get "home/index"
  match "/customers" => "home#customers"
  match "/about" => "home#about"
  match "/contact" => "home#contact"
  match "/oops" => "home#oops"
  match "/news" => "home#news"
  post "/subscribe" => "mailing_list#create", as: :create_mailinglist_subscription


  constraints(Subdomain) do
    authenticated :user do
      match "/" => "dashboard#index"
    end
    match "/" => "dashboard#public"
    resources :pages
    resources :courses do
      resources :course_sessions
    end
  end

  root :to => 'home#index'

  resources :accounts
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  before_filter :requires_current_account
  before_filter :requires_site_admin, except: [:index, :show]
  
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.by_account(@current_account)
    @course_index = params[:crs].nil? ? 0 : params[:crs].to_i

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.by_account(@current_account).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.by_account(@current_account).find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])
    @course.account = @current_account

    respond_to do |format|
      if @course.save
        format.html { redirect_to courses_path, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.by_account(@current_account).find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to courses_path, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.by_account(@current_account).find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course, html: {role: 'form'}) do |f| %>
    <% if @course.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

            <ul>
                <% @course.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="row">
        <div class="col-lg-3">
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control", placeholder: "e.g. 'Butterflies' or 'M-F Mornings'" %>
            </div>

            <div class="form-group">
                <%= f.label :age_group %>
                <%= f.text_field :age_group, class: "form-control", placeholder: "Ages 3-5" %>
            </div>

            <div class="form-group">
                <%= f.label :days_description %>
                <%= f.text_field :days_description, class: "form-control", placeholder: "Monday through Friday" %>
            </div>


            <div class="form-group">
                <%= f.label :class_time_description %>
                <%= f.text_field :class_time_description, class: "form-control", placeholder: "9am to 11am" %>
            </div>

            <div class="form-group">
                <%= f.label :tuition_description %>
                <%= f.text_field :tuition_description, class: "form-control", placeholder: "$130/month" %>
            </div>

            <div class="btn-group">
                <%= f.submit class: "btn btn-success btn-small" %>
                <% if buttons.include?(:show) %>
                    <%= link_to 'Show', @course, class: "btn btn-primary btn-small" %>
                <% end %>
                <% if buttons.include?(:back) %>
                    <%= link_to 'Back', courses_path, class: "btn btn-warning btn-small" %>
                <% end %>
            </div>
        </div>
        <div class="col-lg-9">
            <div class="form-group">
                <%= f.label :long_description %>
                <%= f.text_area :long_description, class: "redactor" %>
            </div>
        </div>
    </div>
<% end %>

app/views/courses/_single_content.html.erb
        <div class="row">
          <div class="col-lg-4">
            <h4><%= course.name %></h4>
            <dl>
              <dt>Class Shedule<dt>
              <dd><%= course.days_description %> at <%= course.class_time_description %>
              <dt>Appropriate Ages</dt>
              <dd><%= course.age_group %></dd>
              <dt>Tuition</dt>
              <dd><%= course.tuition_description %></dd>
            </dl>
          </div>
          <div class="col-lg-5">
            <div class="panel">
              <div class="panel-heading"><strong>Available Sessions</strong>
                <small><%= link_to 'New Session', new_course_course_session_path(course) %></small>
              </div>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Session</th>
                    <th>Schedule</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% course.course_sessions.each do |session| %>
                  <tr class="<%= session_status_class(session.status) %>">
                    <td><%= session.name %></td>
                    <!-- TODO - this is only mocked. -->
                    <td><a href="#" class="btn btn-xs btn-default">View</a></td>
                    <td><%= session.status_description %></td>
                  </tr>
                  <% end %>
                  <% if course.course_sessions.empty? %>
                  <tr>
                    <td colspan="3"><%= link_to 'New Course Session', new_course_course_session_path(course), class: "btn btn-sm btn-success" %></td>
                  </tr>
                  <% end %>
                  <!--
                  <tr class="danger">
                    <td>Spring 2013</td>
                    <td><a href="#" class="btn btn-small btn-default">View</a></td>
                    <td>Closed</td>
                  </tr>
                  <tr class="warning">
                    <td>Fall 2013</td>
                    <td><a href="#" class="btn btn-small btn-default">View</a></td>
                    <td>Waitlisted</td>
                  </tr>
                  <tr class="success">
                    <td>Fall 2013</td>
                    <td><a href="#" class="btn btn-small btn-default">View</a></td>
                    <td>Open</td>
                  </tr> -->
                </tbody>
              </table>
            </div>
          </div>
          <div class="col-lg-3">
            <% if user_signed_in? && current_user.is_site_admin == true %>
            <div class="panel">
              <div class="panel-heading">Actions</div>
              <div class="btn-group btn-group-justified">
                <%= link_to raw('<span class="glyphicon glyphicon-eye-open"></span>'), course, class: "btn btn-default btn-sm" %>
                <%= link_to raw('<i class="glyphicon glyphicon-edit"></i>'), edit_course_path(course), class: "btn btn-sm btn-default" %>
                <%= link_to raw('<i class="glyphicon glyphicon-remove"></i>'), course, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
                <%= link_to raw('<i class="glyphicon glyphicon-plus"></i>'), new_course_path, class: "btn btn-sm btn-success" %>
              </div>
            </div>
            <% end %> <!-- is site admin -->
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="panel">
              <div class="panel-heading"><strong>Course Description</strong></div>
              <%= course.long_description.html_safe %>
            </div>
          </div>
        </div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render partial: 'form', locals: { buttons: [:show, :back] } %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>


<div class="row">
  <div class="col-lg-2">
    <ul class="nav nav-pills nav-stacked">
      <% @courses.each_with_index do |course, index| %>
        <li <%= 'class=active' if index == @course_index %>><a href="#course<%= index.to_s %>" data-toggle="pill"><%= course.name %></a></li>
      <% end %>
    </ul>
  </div>
  <div class="col-lg-10">
    <div class="pill-content">
      <% @courses.each_with_index do |course, index| %>
        <div id="course<%= index.to_s %>" class="pill-pane <%= 'active' if index == @course_index %>">
          <%= render partial: "single_content", locals: { course: course } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render partial: 'form', locals: { buttons: [:back] } %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="btn-group">
  <%= link_to 'Edit', edit_course_path(@course), class: "btn btn-sm btn-warning" %>
  <%= link_to 'Back', courses_path, class: "btn btn-sm btn-primary" %>
</div>

<%= render partial: "single_content", locals: { course: @course } %>