config/routes.rb
Premin::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "dashboard/index"

  devise_for :users

  get "home/index"
  match "/customers" => "home#customers"
  match "/about" => "home#about"
  match "/contact" => "home#contact"
  match "/oops" => "home#oops"
  match "/news" => "home#news"
  post "/subscribe" => "mailing_list#create", as: :create_mailinglist_subscription


  constraints(Subdomain) do
    authenticated :user do
      match "/" => "dashboard#index"
    end
    match "/" => "dashboard#public"
    resources :pages
    resources :courses do
      resources :course_sessions
    end
  end

  root :to => 'home#index'

  resources :accounts
end

app/views/layouts/_messages.html.erb
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="alert <%= flash_class(level) %>">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= favicon_link_tag  %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <%= link_to "Premin", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav pull-left">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Courses", courses_path %></li>
          <!-- Begin: Admin Menu -->
          <% if user_signed_in? && current_user.is_site_admin %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Pages", pages_path %></li>
            </ul>
          </li>
          <% end %> 
          <!-- End: Admin Menu -->
        </ul>
        <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= gravatar_image_tag current_user.email, gravatar: { size: 25 } %>
                    <%= current_user.name %>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
                    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
                </ul>
            </li>
            <% else %>
              <% if is_root_domain? || can_sign_up? %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
        </ul>
      </div>
    </div>


    <div class="container">
        <!-- START CONTENT YIELD -->
        <%= render "layouts/messages" %>
        <%= yield %>
        <!-- END CONTENT YIELD -->
    </div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= favicon_link_tag  %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <%= link_to "Premin", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav pull-left">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "News", news_path %></li>
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Our Customers", customers_path %></li>
          <li><%= link_to "Contact Us", contact_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= gravatar_image_tag current_user.email, gravatar: { size: 25 } %>
                    <%= current_user.name %>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
                    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                    <li><%= link_to 'Edit Account', edit_account_path(current_user.account) %></li>
                </ul>
            </li>
            <% else %>
              <% if is_root_domain? || can_sign_up? %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
        </ul>
      </div>
    </div>


    <div class="container">
        <!-- START CONTENT YIELD -->
        <%= render "layouts/messages" %>
        <%= yield %>
        <!-- END CONTENT YIELD -->
    </div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>