config/routes.rb
Premin::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'

  get "dashboard/index"

  devise_for :users

  get "home/index"
  match "/customers" => "home#customers"
  match "/about" => "home#about"
  match "/contact" => "home#contact"
  match "/oops" => "home#oops"
  match "/news" => "home#news"
  post "/subscribe" => "mailing_list#create", as: :create_mailinglist_subscription


  constraints(Subdomain) do
    authenticated :user do
      match "/" => "dashboard#index"
    end
    match "/" => "dashboard#public"
    resources :pages
    resources :courses do
      resources :course_sessions
    end
  end

  root :to => 'home#index'

  resources :accounts
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users

  belongs_to :owner, class_name: "User", foreign_key: "user_id"

  attr_accessible :subdomain, :name

  VALID_SUBDOMAIN_FORMAT = /^(?![0-9]+$)(?!-)[a-zA-Z0-9-]{,63}(?<!-)$/i
  validates :subdomain, presence: true, uniqueness: { case_sensitive: false }, format: { with: VALID_SUBDOMAIN_FORMAT }
  validates :name, presence: true

  CAN_SIGN_UP = Rails.application.config.allow_account_sign_up
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!, except: :index
  before_filter :verify_owner!, except: [:index, :new, :create]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    #@account = Account.new

    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render json: @account }
    #end
    redirect_to '/oops'
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    #@account = Account.new(params[:account])

    #respond_to do |format|
    #  if @account.save
    #    format.html { redirect_to @account, notice: 'Account was successfully created.' }
    #    format.json { render json: @account, status: :created, location: @account }
    #  else
    #    format.html { render action: "new" }
    #    format.json { render json: @account.errors, status: :unprocessable_entity }
    #  end
    #end
    redirect_to '/oops'
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    #@account = Account.find(params[:id])
    #@account.destroy

    #respond_to do |format|
    #  format.html { redirect_to accounts_url }
    #  format.json { head :no_content }
    #end
    redirect_to '/oops'
  end

  def verify_owner!
    valid = true

    unless user_signed_in?
      redirect_to new_user_session_path
      valid = false
    end

    @account = Account.find(params[:id])
    unless current_user == @account.owner
      redirect_to '/oops'
      valid = false
    end

    valid
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= account.name %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @account.name %>
</p>


<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>